name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Core
          user: omegapaulo
          committer_message: "chore: update metrics"
          
          # Display
          template: classic
          base: header, activity, community, repositories
          
          plugin_isocalendar: yes
          
          plugin_introduction: yes
          
          plugin_habits: yes

          plugin_followup: yes
          plugin_followup_sections: repositories, user
          
          plugin_lines: yes
          
          plugin_achievements: yes
          plugin_achievements_threshold: B
            
        # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.   
          
          
      - name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
              html, tex, dockerfile, makefile, qmake, lex, cmake,
              gnuplot
          plugin_languages_details: bytes-size, percentage
          

        
