name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Core
          user: omegapaulo
          #config_timezone: Asia/Calcutta
          committer_message: "chore: update metrics"
          
          # Display
          template: classic
          base: header, activity, community, repositories
          
          #plugin_isocalendar: yes
          
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 2
          
          #plugin_introduction: yes
          
          plugin_habits: yes
          
          #plugin_followup: yes
          #plugin_followup_sections: repositories, user
          
          plugin_lines: yes
          
          plugin_activity: yes
          
          #plugin_achievements: yes
          #plugin_achievements_threshold: B
          
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.      
